---
server:
  port: 8989

spring:
  application:
    name: cloud-hystrix-turbine
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#management:
#  port: 9222

#turbine:
#  appConfig: cloud-simple-ui
#  clusterNameExpression: new String('default') #http://stackoverflow.com/questions/28365202/spring-boot-eureka-server-hystrix-with-turbine-empty-turbine-stream